version: '3.8'

services:
  frontend:
    build: ./frontend
    image: frontend
    container_name: front
    ports:
      - "5137:5137"
    networks:
      - net
  
  backend:
    build: ./backend
    image: backend
    container_name: back
    networks:
      - net

networks:
  net:
    external: true