version: '1'
services:
  db:
    build:
      context: .
      dockerfile: DockerDB
    container_name: MYSQL_CONTAINER
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: